[package]
name = "async_udp_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async_udp_server = {path = "../async_udp_server"}
tokio = {version = "1.20", features =["time"]}