[package]
name = "smart_outlet_using_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

iced = { version = "0.4.2", features = ["smol"]}
# iced = "0.4.2"
rand = "0.8.5"