services:
  postgres:
    container_name: sh_pg
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: sh
      POSTGRES_USER: sh
      POSTGRES_DB: sh
    # networks:
    #   static-network:
    #   ipv4_address: 127.0.0.1
    # hostname: 127.0.0.1
    ports:
      - 5432:5432
  #   deploy:
  #     resources:
  #       limits:
  #         memory: '512M'
  #         cpus: '1'
  # smart-home-server:
  #   build: .
  #   links:
  #     - postgres
  #   environment:
  #     SERVER.HOST: 0.0.0.0
  #     SERVER.PORT: 8080
  #     PG.USER: sh
  #     PG.PASSWORD: sh
  #     PG.HOST: postgres
  #     PG.PORT: 5432
  #     PG.DBNAME: sh
  #     PG.POOL.MAX_SIZE: 20
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1G
  #         cpus: 2
  #   ports:
  #     - 8080:0000


    